# Generated by Django 2.2.4 on 2019-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('option_left', models.CharField(max_length=50)),
                ('option_right', models.CharField(max_length=50)),
            ],
        ),
    ]
